void readysetgo()
{
    system("cls");
    printf("\n\n\n\n\n\n\n\n\t\t\tReady . . . . .");
    Sleep(2000);
    system("cls");
    printf("\n\n\t\t");
    printf("\n\t\t\t\t ################ ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t ################ ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t ################ ");
    printf("\n");
    Sleep(1000);
    system("cls");
    printf("\n\n\t\t");
    printf("\n\t\t\t\t ################ ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t ################ ");
    printf("\n\t\t\t\t #                ");
    printf("\n\t\t\t\t #                ");
    printf("\n\t\t\t\t #                ");
    printf("\n\t\t\t\t #                ");
    printf("\n\t\t\t\t #                ");
    printf("\n\t\t\t\t #                ");
    printf("\n\t\t\t\t #                ");
    printf("\n\t\t\t\t ################ ");
    printf("\n");
    Sleep(1000);
    system("cls");
    printf("\n\n\t\t");
    printf("\n\t\t\t\t               ## ");
    printf("\n\t\t\t\t              # # ");
    printf("\n\t\t\t\t             #  # ");
    printf("\n\t\t\t\t            #   # ");
    printf("\n\t\t\t\t           #    # ");
    printf("\n\t\t\t\t          #     # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n\t\t\t\t                # ");
    printf("\n");
    Sleep(1000);
}
